spring:
  config:
    name: Stastistics collector [collect-statistics]
        
server:
  port:    9080
  
statistics:
  address:            rd-statistics.rd-tools.addvalueit.svc.tutum.io
  port:               2003
  reportingInterval:  7

    
